    name: Run Python Script

    on:
      push:
        branches: master
      pull_request:
        branches: master

    jobs:
      build:
        runs-on: ubuntu-latest # Specify the runner environment

        steps:
        - uses: actions/checkout@v4 # Checkout the repository code
          name: Checkout Repository

        - uses: actions/setup-python@v5 # Set up Python environment
          name: Set up Python
          with:
            python-version: '3.13.9' # Specify the Python version to use

        - name: Install Dependencies # (Optional) Install Python packages if needed
          run: pip install -r requirements.txt # Assuming a requirements.txt file exists

        - name: Run Python Script
          run: python preprocessing/automate_Thoriq_Dhiya_A.py # Execute your Python script
